using System;
using System.Windows.Forms;
using System.Windows.Forms.DataVisualization.Charting;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        Load += Form1_Load; // Attach the Load event handler
    }

    private void Form1_Load(object sender, EventArgs e)
    {
        // Create a new Chart control
        Chart chart1 = new Chart();
        chart1.Parent = this; // Set the parent to the current form
        chart1.Dock = DockStyle.Fill; // Dock the chart to fill the form

        // Create a ChartArea
        ChartArea chartArea1 = new ChartArea();
        chart1.ChartAreas.Add(chartArea1);

        // Create a Series for the data
        Series series1 = new Series();
        series1.Name = "MySeries";
        series1.ChartType = SeriesChartType.Column; // Set chart type to Column (bar chart)
        chart1.Series.Add(series1);

        // Add data points to the series
        series1.Points.AddXY("Category A", 10);
        series1.Points.AddXY("Category B", 25);
        series1.Points.AddXY("Category C", 15);
        series1.Points.AddXY("Category D", 30);

        // Optional: Set chart title
        Title title1 = new Title("Sample Bar Chart");
        chart1.Titles.Add(title1);
    }

    // This method is typically generated by the designer for a Windows Form
    private void InitializeComponent()
    {
        this.SuspendLayout();
        // Form1
        this.ClientSize = new System.Drawing.Size(600, 400);
        this.Name = "Form1";
        this.Text = "Simple Data Visualization";
        this.ResumeLayout(false);
    }
}
